In [4]:

%load_ext autoreload
%autoreload 2
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import numpy as np
from get_homography import *
from stitch3 import *


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
img1=cv2.imread('images/mountain-left.jpg')
img2=cv2.imread('images/mountain-middle.jpg')
img3=cv2.imread('images/mountain-right.jpg')
# img1=cv2.imread('images/firewatch-left.jpg')
# img2=cv2.imread('images/firewatch-middle.jpg')
# img3=cv2.imread('images/firewatch-right.jpg')
# img1=cv2.imread('images/small-left.jpg')
# img2=cv2.imread('images/small-middle.jpg')
# img3=cv2.imread('images/small-right.jpg')
# img1=cv2.imread('images/web-left.jpg')
# img2=cv2.imread('images/web-middle.jpg')
# img3=cv2.imread('images/web-right.jpg')

HLM = get_homography(img1,img2)
HMR = get_homography(img2,img3)

5459
5468
Rmax1.4142135623730951
(486,)
(466,)
MaxInlierCount466
Final H[[ 1.12759583e+00 -5.48300669e-02 -1.64641181e+02]
 [ 1.08864645e-01  1.07987233e+00 -3.50606423e+00]
 [ 3.53522133e-04 -4.82018487e-05  1.00000000e+00]]
5468
5799
Rmax1.4142135623730951
(1243,)
(1236,)
MaxInlierCount1236
Final H[[ 1.12219835e+00 -1.23122225e-02 -1.53128909e+02]
 [ 6.23772326e-02  1.07271930e+00  7.94488910e+00]
 [ 3.33599689e-04 -4.89636294e-05  1.00000000e+00]]


In [11]:
canvas = stitch3(img1,img2,img3,HLM,HMR)

cv2.imwrite("res.png",canvas)

True

In [ ]:
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
canvas[:,:,0] = clahe.apply(canvas[:,:,0])
canvas[:,:,1] = clahe.apply(canvas[:,:,1])
canvas[:,:,2] = clahe.apply(canvas[:,:,2])
# canvas[:,:,0] = cv2.equalizeHist(canvas[:,:,0])
# canvas[:,:,1] = cv2.equalizeHist(canvas[:,:,1])
# canvas[:,:,2] = cv2.equalizeHist(canvas[:,:,2])