In [92]:

%load_ext autoreload
%autoreload 2
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import numpy as np
from get_homography import *
from stitch_neo import *
import sys


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [93]:
# img1=cv2.imread('images/mountain-left.jpg')
# img2=cv2.imread('images/mountain-middle.jpg')
# img3=cv2.imread('images/mountain-right.jpg')
# img1=cv2.imread('images/firewatch-left.jpg')
# img2=cv2.imread('images/firewatch-middle.jpg')
# img3=cv2.imread('images/firewatch-right.jpg')
# img1=cv2.imread('images/small-left.jpg')
# img2=cv2.imread('images/small-middle.jpg')
# img3=cv2.imread('images/small-right.jpg')
# img1=cv2.imread('images/web-left.jpg')
# img2=cv2.imread('images/web-middle.jpg')
# img3=cv2.imread('images/web-right.jpg')
# img1=cv2.imread('images/josh_image_left.jpg')
# img2=cv2.imread('images/josh_image_middle.jpg')
# img3=cv2.imread('images/josh_image_right.jpg')
img1=cv2.imread('images/left.jpg')
img2=cv2.imread('images/middle.jpg')
img3=cv2.imread('images/right.jpg')

HLM = get_homography(img1,img2)
HMR = get_homography(img2,img3)

(234,)
(181,)
MaxInlierCount181
Final H[[ 1.79338574e+00 -4.74117647e-02 -6.31658148e+02]
 [ 3.55514221e-01  1.56321149e+00 -2.52295940e+02]
 [ 7.81512924e-04  7.73161793e-05  1.00000000e+00]]
(144,)
(103,)
MaxInlierCount103
Final H[[ 2.16988247e+00 -9.24235672e-02 -9.30996576e+02]
 [ 5.26435475e-01  1.86638940e+00 -3.97593640e+02]
 [ 1.20926635e-03  5.13633107e-05  1.00000000e+00]]


In [94]:
canvas = stitch_neo(img1,img2,img3,HLM,HMR)
cv2.imwrite("output.png",canvas)


(720, 624)
(720, 527)


True