In [75]:

%load_ext autoreload
%autoreload 2
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import numpy as np
from get_homography import *
from stitch_neo import *
import sys


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [76]:
# img1=cv2.imread('images/mountain-left.jpg')
# img2=cv2.imread('images/mountain-middle.jpg')
# img3=cv2.imread('images/mountain-right.jpg')
# img1=cv2.imread('images/firewatch-left.jpg')
# img2=cv2.imread('images/firewatch-middle.jpg')
# img3=cv2.imread('images/firewatch-right.jpg')
# img1=cv2.imread('images/small-left.jpg')
# img2=cv2.imread('images/small-middle.jpg')
# img3=cv2.imread('images/small-right.jpg')
# img1=cv2.imread('images/web-left.jpg')
# img2=cv2.imread('images/web-middle.jpg')
# img3=cv2.imread('images/web-right.jpg')
img1=cv2.imread('images/josh_image_left.jpg')
img2=cv2.imread('images/josh_image_middle.jpg')
img3=cv2.imread('images/josh_image_right.jpg')

HLM = get_homography(img1,img2)
HMR = get_homography(img2,img3)

2399
10360
Rmax2.8284271247461903
(420,)
(414,)
MaxInlierCount414
Final H[[ 1.07669893e+00 -9.28041352e-03 -2.10951011e+02]
 [ 5.85045246e-02  1.06038500e+00 -2.47687509e+01]
 [ 1.61237745e-04  1.69259132e-05  1.00000000e+00]]
10360
5184
Rmax1.0
(258,)
(249,)
MaxInlierCount249
Final H[[ 1.08028767e+00  4.21688302e-03 -2.36015616e+02]
 [ 4.76159673e-02  1.06287011e+00 -1.59246591e+01]
 [ 1.74952514e-04  1.14714540e-05  1.00000000e+00]]


In [85]:
canvas = stitch_neo(img1,img2,img3,HLM,HMR)
cv2.imwrite("output.png",canvas)


(599, 256)
(600, 233)


True