In [86]:

%load_ext autoreload
%autoreload 2
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import numpy as np
from get_homography import *
from stitch_neo import *
import sys


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [87]:
# img1=cv2.imread('images/mountain-left.jpg')
# img2=cv2.imread('images/mountain-middle.jpg')
# img3=cv2.imread('images/mountain-right.jpg')
# img1=cv2.imread('images/firewatch-left.jpg')
# img2=cv2.imread('images/firewatch-middle.jpg')
# img3=cv2.imread('images/firewatch-right.jpg')
# img1=cv2.imread('images/small-left.jpg')
# img2=cv2.imread('images/small-middle.jpg')
# img3=cv2.imread('images/small-right.jpg')
# img1=cv2.imread('images/web-left.jpg')
# img2=cv2.imread('images/web-middle.jpg')
# img3=cv2.imread('images/web-right.jpg')
# img1=cv2.imread('images/josh_image_left.jpg')
# img2=cv2.imread('images/josh_image_middle.jpg')
# img3=cv2.imread('images/josh_image_right.jpg')
img1=cv2.imread('images/left.jpg')
img2=cv2.imread('images/middle.jpg')
img3=cv2.imread('images/right.jpg')

HLM = get_homography(img1,img2)
HMR = get_homography(img2,img3)

(174,)
(139,)
MaxInlierCount139
Final H[[ 1.97982941e+00 -6.36638973e-02 -9.42609751e+02]
 [ 3.38245945e-01  1.64389037e+00 -2.82325343e+02]
 [ 7.57455172e-04  1.82811600e-06  1.00000000e+00]]
(88,)
(59,)
MaxInlierCount59
Final H[[ 2.03345444e+00 -4.50368086e-02 -1.06656586e+03]
 [ 3.48122326e-01  1.68992158e+00 -2.99203428e+02]
 [ 8.17515311e-04 -2.58374918e-05  1.00000000e+00]]


In [88]:
canvas = stitch_neo(img1,img2,img3,HLM,HMR)
cv2.imwrite("output.png",canvas)


(720, 809)
(720, 753)


True