In [107]:

%load_ext autoreload
%autoreload 2
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import numpy as np
from get_homography import *
from mymosaic import *
import sys


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [108]:
# img1=cv2.imread('images/mountain-left.jpg')
# img2=cv2.imread('images/mountain-middle.jpg')
# img3=cv2.imread('images/mountain-right.jpg')
# img1=cv2.imread('images/firewatch-left.jpg')
# img2=cv2.imread('images/firewatch-middle.jpg')
# img3=cv2.imread('images/firewatch-right.jpg')
# img1=cv2.imread('images/web-left.jpg')
# img2=cv2.imread('images/web-middle.jpg')
# img3=cv2.imread('images/web-right.jpg')
# img1=cv2.imread('images/josh_image_left.jpg')
# img2=cv2.imread('images/josh_image_middle.jpg')
# img3=cv2.imread('images/josh_image_right.jpg')
img1=cv2.imread('images/shoemaker-left.jpg')
img2=cv2.imread('images/shoemaker-middle.jpg')
img3=cv2.imread('images/shoemaker-right.jpg')
# img1=cv2.imread('images/gym-left.jpg')
# img2=cv2.imread('images/gym-middle.jpg')
# img3=cv2.imread('images/gym-right.jpg')

HLM = get_homography(img1,img2)
HMR = get_homography(img2,img3)

(234,)
(183,)
MaxInlierCount183
Final H[[ 1.80238217e+00 -5.54647942e-02 -6.33276688e+02]
 [ 3.63262427e-01  1.55236346e+00 -2.52098318e+02]
 [ 8.01016697e-04  5.24320005e-05  1.00000000e+00]]
(138,)
(102,)
MaxInlierCount102
Final H[[ 2.19084227e+00 -9.10740000e-02 -9.42150165e+02]
 [ 5.31636100e-01  1.87521523e+00 -3.99838879e+02]
 [ 1.22542753e-03  5.52399907e-05  1.00000000e+00]]


In [109]:
canvas = mymosaic(img1,img2,img3,HLM,HMR)
cv2.imwrite("output.png",canvas)
